# Generated by Django 5.1 on 2024-08-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebooks',
            name='color',
            field=models.ManyToManyField(related_name='note_color', to='main.color'),
        ),
    ]
